export const AGREGAR_CUENTA = "AGREGAR_CUENTA"
export const AGREGAR_CUENTA_EXITO = "AGREGAR_CUENTA_EXITO"
export const AGREGAR_CUENTA_ERROR = "AGREGAR_CUENTA_ERROR"


//Obtener cuentas 

export const OBTENER_CUENTAS = "OBTENER_CUENTAS"
export const OBTENER_CUENTAS_EXITO = "OBTENER_CUENTAS_EXITO"
export const OBTENER_CUENTAS_ERROR = "OBTENER_CUENTAS_ERROR"


//App
export const CUENTA_ACTUAL = "CUENTA_ACTUAL"




export const OBTENER_INFOUSUARIO = "OBTENER_INFOUSUARIO"
export const OBTENER_INFOUSUARIO_EXITO = "OBTENER_INFOUSUARIO_EXITO"
export const OBTENER_INFOUSUARIO_ERROR = "OBTENER_INFOUSUARIO_ERROR"

export const CAMBIAR_PAG = "CAMBIAR_PAG"
export const CHANGE_LAYOUT = "CHANGE_LAYOUT"
export const CHANGE_LAYOUT_SHOW = "CHANGE_LAYOUT_SHOW"
export const CHANGE_META = "CHANGE_META"
export const ACTIVAR_ERROR = "ACTIVAR_ERROR"

export const AGREGAR_INGRESO = "AGREGAR_INGRESO"
export const AGREGAR_INGRESO_EXITO = "AGREGAR_INGRESO_EXITO"
export const AGREGAR_INGRESO_ERROR = "AGREGAR_INGRESO_ERROR"



/* export const AGREGAR_INGRESO = "AGREGAR_INGRESO"
export const AGREGAR_INGRESO_EXITO = "AGREGAR_INGRESO_EXITO"
export const AGREGAR_INGRESO_ERROR = "AGREGAR_INGRESO_ERROR"
 */