export const AGREGAR_CUENTA = "AGREGAR_CUENTA"
export const AGREGAR_CUENTA_EXITO = "AGREGAR_CUENTA_EXITO"
export const AGREGAR_CUENTA_ERROR = "AGREGAR_CUENTA_ERROR"


//Obtener cuentas 

export const OBTENER_CUENTAS = "OBTENER_CUENTAS"
export const OBTENER_CUENTAS_EXITO = "OBTENER_CUENTAS_EXITO"
export const OBTENER_CUENTAS_ERROR = "OBTENER_CUENTAS_ERROR"


//App
export const CUENTA_ACTUAL = "CUENTA_ACTUAL"




export const OBTENER_INFOUSUARIO = "OBTENER_INFOUSUARIO"
export const OBTENER_INFOUSUARIO_EXITO = "OBTENER_INFOUSUARIO_EXITO"
export const OBTENER_INFOUSUARIO_ERROR = "OBTENER_INFOUSUARIO_ERROR"

export const CAMBIAR_PAG = "CAMBIAR_PAG"
export const CHANGE_LAYOUT = "CHANGE_LAYOUT"
export const CHANGE_LAYOUT_SHOW = "CHANGE_LAYOUT_SHOW"
export const CHANGE_META = "CHANGE_META"
export const CHANGE_GASTO = "CHANGE_GASTO"
export const ACTIVAR_ERROR = "ACTIVAR_ERROR"

export const AGREGAR_INGRESO = "AGREGAR_INGRESO"
export const AGREGAR_INGRESO_EXITO = "AGREGAR_INGRESO_EXITO"
export const AGREGAR_INGRESO_ERROR = "AGREGAR_INGRESO_ERROR"


export const AGREGAR_GASTO = "AGREGAR_GASTO"
export const AGREGAR_GASTO_EXITO = "AGREGAR_GASTO_EXITO"
export const AGREGAR_GASTO_ERROR = "AGREGAR_GASTO_ERROR"

export const AGREGAR_META = "AGREGAR_META"
export const AGREGAR_META_EXITO = "AGREGAR_META_EXITO"
export const AGREGAR_META_ERROR = "AGREGAR_META_ERROR"


export const OBTENER_INGRESOS = "OBTENER_INGRESOS"
export const OBTENER_META = "OBTENER_META"
export const OBTENER_GASTOS = "OBTENER_GASTOS"


/*Eliminar y EDITAR*/
export const ELIMINAR_GASTO = "ELIMINAR_GASTO"
export const ELIMINAR_GASTO_ERROR = "ELIMINAR_GASTO_ERROR"
export const ELIMINAR_GASTO_EXITO = "ELIMINAR_GASTO_EXITO"

export const ELIMINAR_INGRESO = "ELIMINAR_INGRESO"
export const ELIMINAR_INGRESO_ERROR = "ELIMINAR_INGRESO_ERROR"
export const ELIMINAR_INGRESO_EXITO = "ELIMINAR_INGRESO_EXITO"






//CALCULOS
export const OBTENER_DATOS ="OBTENER_DATOS"



//ADMINISTRADOR
export const SHOW_ADD = "SHOW_ADD"
export const SHOW_ADD_FALSE = "SHOW_ADD_FALSE"
export const SHOW_PROYECTO = "SHOW_PROYECTO"
export const SHOW_PROYECTO_FALSE = "SHOW_PROYECTO_FALSE"


export const OBTENER_PROYECTOS = "OBTENER_PROYECTOS"
export const OBTENER_PROYECTOS_EXITO = "OBTENER_PROYECTOS_EXITO"
export const OBTENER_PROYECTOS_ERROR = "OBTENER_PROYECTOS_ERROR"

export const ADD_PROYECTO = "ADD_PROYECTO"
export const ADD_PROYECTO_EXITO = "ADD_PROYECTO_EXITO"
export const ADD_PROYECTO_ERROR = "ADD_PROYECTO_ERROR"

export const ADD_TAREA = "ADD_TAREA"
export const ADD_TAREA_EXITO = "ADD_TAREA_EXITO"
export const ADD_TAREA_ERROR = "ADD_TAREA_ERROR"


export const ELIMINAR_TAREA = "ELIMINAR_TAREA"
export const ELIMINAR_TAREA_EXITO = "ELIMINAR_TAREA_EXITO"
export const ELIMINAR_TAREA_ERROR = "ELIMINAR_TAREA_ERROR"


export const EDITAR_TAREA = "EDITAR_TAREA"
export const EDITAR_TAREA_EXITO = "EDITAR_TAREA_EXITO"
export const EDITAR_TAREA_ERROR = "EDITAR_TAREA_ERROR"

export const ELIMINAR_PROYECTO = "ELIMINAR_PROYECTO"
export const ELIMINAR_PROYECTO_EXITO = "ELIMINAR_PROYECTO_EXITO"
export const ELIMINAR_PROYECTO_ERROR = "ELIMINAR_PROYECTO_ERROR"

export const ESCRIBIENDO = "ESCRIBIENDO"


export const CAMBIAR_STATE = "CAMBIAR_STATE"
export const CAMBIAR_STATE_EXITO = "CAMBIAR_STATE_EXITO"
export const CAMBIAR_STATE_ERROR = "CAMBIAR_STATE_ERROR"


export const OBTENER_ESCRITOS = "OBTENER_ESCRITOS"
export const OBTENER_ESCRITOS_EXITO = "OBTENER_ESCRITOS_EXITO"
export const OBTENER_ESCRITOS_ERROR = "OBTENER_ESCRITOS_ERROR"

export const AGREGAR_ESCRITO = "AGREGAR_ESCRITO"
export const AGREGAR_ESCRITO_EXITO = "AGREGAR_ESCRITO_EXITO"
export const AGREGAR_ESCRITO_ERROR = "AGREGAR_ESCRITO_ERROR"


export const ELEGIR_ESCRITO = "ELEGIR_ESCRITO"



export const ACTUALIZAR_ESCRITO = "ACTUALIZAR_ESCRITO"
export const ACTUALIZAR_ESCRITO_EXITO = "ACTUALIZAR_ESCRITO_EXITO"
export const ACTUALIZAR_ESCRITO_ERROR = "ACTUALIZAR_ESCRITO_ERROR"






