export const AGREGAR_CUENTA = "AGREGAR_CUENTA"
export const AGREGAR_CUENTA_EXITO = "AGREGAR_CUENTA_EXITO"
export const AGREGAR_CUENTA_ERROR = "AGREGAR_CUENTA_ERROR"


//Obtener cuentas 

export const OBTENER_CUENTAS = "OBTENER_CUENTAS"
export const OBTENER_CUENTAS_EXITO = "OBTENER_CUENTAS_EXITO"
export const OBTENER_CUENTAS_ERROR = "OBTENER_CUENTAS_ERROR"


//App

export const CAMBIAR_PAG = "CAMBIAR_PAG"
